<?php
/** Actual isolated WordPress ZIP verifier and media pipeline tests. No credentials. */
if (PHP_SAPI !== 'cli' || empty($argv[1])) { exit(2); }
$_SERVER['HTTP_HOST']='127.0.0.1:8766'; $_SERVER['SERVER_NAME']='127.0.0.1'; $_SERVER['REQUEST_URI']='/'; require $argv[1];
if (wp_get_environment_type() !== 'local' || (int)get_option('blog_public') !== 0 || !function_exists('bixie_track_attachment_review')) { fwrite(STDERR,"Latest plugin and isolated local noindex site required.\n");exit(2); }
$folder=wp_upload_dir()['basedir'].'/bixie-qa-adversarial-'.wp_generate_uuid4();wp_mkdir_p($folder);$tests=[];$part_ids=[];$attachments=[];$posts=[];$failure=null;
function qb_assert(string $name,bool $ok,array $detail=[]):void{global $tests;$tests[]=['name'=>$name,'passed'=>$ok,'detail'=>$detail];if(!$ok){throw new RuntimeException($name);}}
function qb_zip(string $path,array $files,array $attributes=[]):void{$zip=new ZipArchive();if($zip->open($path,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true){throw new RuntimeException('Cannot create QA ZIP.');}foreach($files as $name=>$bytes){$zip->addFromString($name,$bytes);}foreach($attributes as $name=>$mode){$zip->setExternalAttributesName($name,ZipArchive::OPSYS_UNIX,$mode<<16);}$zip->close();}
function qb_reject(string $label,string $path):void{$rejected=false;$message='';try{bixie_verify_bundle_archive($path);}catch(Throwable $error){$rejected=true;$message=$error->getMessage();}qb_assert($label,$rejected,['rejection'=>$message]);}
try{
 $records=[];$files=[];
 foreach(['front','side','back'] as $i=>$angle){$image=imagecreatetruecolor(1122,1402);$color=imagecolorallocate($image,40+$i*60,100+$i*30,150-$i*30);imagefill($image,0,0,$color);$ink=imagecolorallocate($image,255,255,255);imagestring($image,5,80,120,'ISOLATED SYNTHETIC TEST '.$angle,$ink);$png=$folder.'/test-'.$angle.'.png';$webp=$folder.'/test-'.$angle.'.webp';imagepng($image,$png);imagewebp($image,$webp,80);imagedestroy($image);$key='isolated-qa-bundle-'.$angle;$record=['key'=>$key,'source_file'=>'source-media/'.$key.'.png','file'=>'media/'.$key.'.webp','sha256'=>hash_file('sha256',$png),'display_sha256'=>hash_file('sha256',$webp),'width'=>1122,'height'=>1402,'angle'=>$angle,'native_original'=>true,'native_8k'=>false,'upscaled'=>false,'approved'=>false,'review_status'=>'UNAPPROVED SYNTHETIC CODE FIXTURE','alt'=>'ISOLATED synthetic test canvas, not hairstyle photography'];$records[]=$record;$files[$record['source_file']]=file_get_contents($png);$files[$record['file']]=file_get_contents($webp);}
 $part_id='isolated-qa-bundle-verifier';$part_ids[]=$part_id;$manifest=['bundle_id'=>$part_id,'records'=>$records,'looks'=>[]];$files=['manifest.json'=>wp_json_encode($manifest)]+$files;$valid=$folder.'/valid.zip';qb_zip($valid,$files);$part=bixie_verify_bundle_archive($valid);
 qb_assert('Valid actual PNG/WebP media part is verified and registered',$part['media_count']===3&&$part['files_count']===7);
 $again=bixie_verify_bundle_archive($valid);qb_assert('Identical media part is safely idempotent',!empty($again['already_uploaded']));
 $catalog=['version'=>1,'site'=>[],'pages'=>[],'collections'=>[],'looks'=>[['key'=>'isolated-qa-full-fields-look','title'=>'ISOLATED full-field loader regression','status'=>'draft','images'=>$records]]];$catalog_path=$folder.'/catalog.json';file_put_contents($catalog_path,wp_json_encode($catalog));$loaded=Bixie_Importer::load($catalog_path);
 qb_assert('Uploaded roots win when canonical look images also contain full source/file records',$loaded['_path']===$catalog_path&&count(array_filter($loaded['_media'],static fn($r)=>str_starts_with($r['key'],'isolated-qa-bundle-')&&!empty($r['_bundle_root'])))===3);
 $state=['counts'=>['media'=>0,'skipped'=>0],'log'=>[]];$media=new ReflectionMethod(Bixie_Importer::class,'media');
 foreach($loaded['_media'] as $record){if(str_starts_with($record['key'],'isolated-qa-bundle-')){$media->invokeArgs(null,[$record,&$state]);$id=bixie_get_package_attachment($record['key']);$attachments[]=$id;update_post_meta($id,'_bixie_qa_fixture',1);}}
 qb_assert('Three optimized display attachments import from uploaded parts without missing-source errors',$state['counts']['media']===3&&count(array_filter($attachments))===3);
 $id=$attachments[0];$native=bixie_original_source_path($id);$display=get_attached_file($id);$metadata=wp_get_attachment_metadata($id);$draft=wp_insert_post(['post_type'=>'bixie_look','post_title'=>'ISOLATED delivery geometry test','post_status'=>'draft','meta_input'=>['_bixie_qa_fixture'=>1,'bixie_images'=>array_map(static fn($i,$a)=>['id'=>$i,'angle'=>$a,'caption'=>'ISOLATED TEST'],$attachments,['front','side','back'])]]);$posts[]=$draft;$image=bixie_get_look_data($draft)['image'];
 qb_assert('Genuine source PNG and optimized WebP delivery remain separate',str_ends_with($native,'.png')&&str_ends_with($display,'.webp')&&$image['originalUrl']!==$image['url']&&str_ends_with($image['originalUrl'],'.png'));
 qb_assert('API native dimensions and identity come from the actual retained PNG',$image['originalWidth']===1122&&$image['originalHeight']===1402&&bixie_source_fingerprint($id)===$records[0]['sha256']);
 qb_assert('Initial gallery thumbnails use responsive optimized WebP, not original PNG',str_contains($image['thumbnailUrl'],'.webp')&&$image['thumbnailUrl']!==$image['originalUrl']&&!empty($metadata['sizes']['medium_large']));
 qb_assert('Unapproved synthetic media cannot publish a complete look',get_post_status($draft)==='draft'&&!bixie_check_look($draft)['complete']);
 foreach($attachments as $source){update_post_meta($source,'_bixie_review_approved',1);bixie_track_attachment_review(0,$source,'_bixie_review_approved');}wp_update_post(['ID'=>$draft,'post_status'=>'publish']);qb_assert('Clearly isolated three-source review fixture reaches the real publication gate',get_post_status($draft)==='publish');
 $gone=$native.'.isolated-missing';rename($native,$gone);qb_assert('Missing retained PNG cannot qualify through optimized display fallback',bixie_original_source_path($id)===$native&&!bixie_check_look($draft)['complete']);rename($gone,$native);
 $replacement=$folder.'/same-attachment-replacement.webp';copy($folder.'/test-side.webp',$replacement);update_post_meta($id,'_wp_attached_file',$replacement);
 qb_assert('Same attachment file replacement clears review/provenance and old PNG linkage',!get_post_meta($id,'_bixie_review_approved',true)&&!get_post_meta($id,'_bixie_native_verified',true)&&!get_post_meta($id,'_bixie_original_source_file',true)&&get_post_status($draft)==='draft');
 update_post_meta($id,'_wp_attached_file',$display);
 // A second approval followed by changed bytes at the same path also requires fresh review.
 update_post_meta($id,'_bixie_native_verified',1);update_post_meta($id,'_bixie_review_approved',1);bixie_track_attachment_review(0,$id,'_bixie_review_approved');copy($folder.'/test-back.webp',$display);update_post_meta($id,'_wp_attachment_metadata',array_merge($metadata,['isolated_test_revision'=>1]));
 qb_assert('Changed image bytes under the same attachment path invalidate review',!get_post_meta($id,'_bixie_review_approved',true)&&!get_post_meta($id,'_bixie_native_verified',true));
 $cases=[];$bad=$files;$bad['source-media/../escape.php']='<?php exit;';$cases['Archive traversal rejected']=$bad;
 $bad=$files;$bad['media/unlisted.png']=$files[$records[0]['source_file']];$cases['Unlisted extra file rejected']=$bad;
 $bad=$files;unset($bad[$records[0]['file']]);$cases['Missing declared derivative rejected']=$bad;
 $bad=$files;$wrong=$manifest;$wrong['bundle_id']='isolated-qa-wrong-checksum';foreach($wrong['records'] as &$r){$r['key'].='-checksum-test';}unset($r);$wrong['records'][0]['sha256']=str_repeat('0',64);$bad['manifest.json']=wp_json_encode($wrong);$cases['Wrong original checksum rejects whole part']=$bad;
 $bad=$files;$bad['source-media/ISOLATED-qa-bundle-front.png']=$files[$records[0]['source_file']];$cases['Case-colliding archive names rejected']=$bad;
 $bad=$files;$different=$manifest;$different['records'][0]['alt']='CHANGED PACKAGE COPY';$bad['manifest.json']=wp_json_encode($different);$cases['Changed existing bundle ID preserves original files']=$bad;
 $bad=$files;unset($bad['manifest.json']);$cases['Missing root manifest rejected']=$bad;
 foreach($cases as $label=>$content){$path=$folder.'/bad-'.count($tests).'.zip';qb_zip($path,$content);qb_reject($label,$path);}
 $path=$folder.'/symlink.zip';qb_zip($path,$files,[$records[0]['source_file']=>0120777]);qb_reject('Archive symbolic link rejected',$path);
 $path=$folder.'/expanded-file.zip';qb_zip($path,['manifest.json'=>wp_json_encode($manifest),'media/bomb.png'=>str_repeat('A',33*MB_IN_BYTES)]);qb_reject('Oversized expanded file rejected before extraction',$path);
 $path=$folder.'/expanded-total.zip';qb_zip($path,['manifest.json'=>wp_json_encode($manifest),'media/bomb1.png'=>str_repeat('A',23*MB_IN_BYTES),'media/bomb2.png'=>str_repeat('B',23*MB_IN_BYTES),'media/bomb3.png'=>str_repeat('C',23*MB_IN_BYTES)]);qb_reject('ZIP expansion total bounded before extraction',$path);
 $video='This is plain text, not an MP4 container.';$fake=['bundle_id'=>'isolated-qa-fake-video','records'=>[['key'=>'isolated-qa-fake-film','file'=>'video/fake.mp4','sha256'=>hash('sha256',$video)]],'looks'=>[]];$path=$folder.'/fake-video.zip';qb_zip($path,['manifest.json'=>wp_json_encode($fake),'video/fake.mp4'=>$video]);qb_reject('Bogus MP4 with a valid SHA-256 checksum rejected',$path);
 $text='<?php echo "not image media";';$fake=['bundle_id'=>'isolated-qa-fake-image','records'=>[['key'=>'isolated-qa-fake-image','file'=>'media/fake.png','sha256'=>hash('sha256',$text)]],'looks'=>[]];$path=$folder.'/fake-image.zip';qb_zip($path,['manifest.json'=>wp_json_encode($fake),'media/fake.png'=>$text]);qb_reject('Script bytes renamed as image rejected',$path);
 $changed=$manifest;$changed['bundle_id']='isolated-qa-reused-key';$changed['records'][0]['sha256']=$records[1]['sha256'];$bad=$files;$bad['manifest.json']=wp_json_encode($changed);$bad[$records[0]['source_file']]=$files[$records[1]['source_file']];$path=$folder.'/reused-key.zip';qb_zip($path,$bad);qb_reject('Different original cannot silently replace an existing uploaded asset key',$path);
 qb_assert('Existing source files survived rejected overwrite unchanged',hash_file('sha256',bixie_bundle_base().'/'.$part_id.'/'.$records[0]['source_file'])===$records[0]['sha256']);
}catch(Throwable $error){$failure=$error->getMessage();}
finally{foreach($posts as $id){wp_delete_post($id,true);}foreach($attachments as $id){$original_delivery=get_post_meta($id,'_bixie_reviewed_delivery_file',true);wp_delete_attachment($id,true);if(is_string($original_delivery)&&is_file($original_delivery)&&str_starts_with($original_delivery,wp_upload_dir()['basedir'])){unlink($original_delivery);}}$parts=(array)get_option('bixie_media_bundle_parts',[]);foreach($part_ids as $id){if(isset($parts[$id])){$root=bixie_bundle_base().'/'.$id;bixie_bundle_remove_stage($root);unset($parts[$id]);}}update_option('bixie_media_bundle_parts',$parts,false);if(is_dir($folder)){bixie_bundle_remove_stage($folder);}bixie_invalidate_catalog();}
$report=['environment'=>['wordpress'=>get_bloginfo('version'),'php'=>PHP_VERSION],'method'=>'Actual isolated WordPress execution of verifier/importer/source-review hooks; local adversarial archives and explicitly synthetic canvases, not production media. Authenticated HTTP upload checks are a separate report.','passed'=>$failure===null,'checks'=>$tests,'failure'=>$failure,'approvedProductionImages'=>0];$json=wp_json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)."\n";if(!empty($argv[2])){file_put_contents($argv[2],$json);}echo $json;exit($report['passed']?0:1);
