<?php
/** Real WordPress orchestration/security with simulated HTTP transport, not a live release download. */
if(PHP_SAPI!=='cli'||empty($argv[1])){exit(2);}$_SERVER['HTTP_HOST']='127.0.0.1:8766';$_SERVER['SERVER_NAME']='127.0.0.1';$_SERVER['REQUEST_URI']='/';require $argv[1];
if(wp_get_environment_type()!=='local'||(int)get_option('blog_public')!==0||!function_exists('bixie_download_step')){fwrite(STDERR,"Latest plugin and isolated QA site required.\n");exit(2);}
$tests=[];$failure=null;$folder=wp_upload_dir()['basedir'].'/isolated-download-qa-'.wp_generate_uuid4();wp_mkdir_p($folder);$index_path=BIXIE_LIBRARY_DIR.'content/release-index.json';$old_index=is_file($index_path)?file_get_contents($index_path):null;$old_state=get_option('bixie_media_download_state',null);$part_ids=[];$interceptor=null;$calls=[];
function qd_assert(string $name,bool $ok,array $detail=[]):void{global $tests;$tests[]=['name'=>$name,'passed'=>$ok,'detail'=>$detail];if(!$ok){throw new RuntimeException($name);}}
try{
 qd_assert('Only HTTPS URLs in the embedded repository allowlist are accepted',bixie_release_url_allowed('https://raw.githubusercontent.com/imahmad-malik/check.txt/revision/media/part.zip')&&!bixie_release_url_allowed('http://raw.githubusercontent.com/imahmad-malik/check.txt/a.zip')&&!bixie_release_url_allowed('https://example.invalid/a.zip')&&!bixie_release_url_allowed('https://raw.githubusercontent.com/other/repo/a.zip')&&!bixie_release_url_allowed('https://user:secret@github.com/imahmad-malik/check.txt/a.zip'));
 file_put_contents($index_path,wp_json_encode(['version'=>1,'release'=>'isolated-empty-test','parts'=>[]]));$rejected=false;try{bixie_download_start();}catch(Throwable $error){$rejected=true;}qd_assert('Empty release index produces no fake download or activation fetch',$rejected);
 $canvas=imagecreatetruecolor(1048,1310);$color=imagecolorallocate($canvas,20,120,170);imagefill($canvas,0,0,$color);$png=$folder.'/synthetic.png';imagepng($canvas,$png);imagedestroy($canvas);$hash=hash_file('sha256',$png);$record=['key'=>'isolated-qa-download-source','file'=>'media/isolated-qa-download.png','sha256'=>$hash,'approved'=>false,'native_original'=>true,'upscaled'=>false,'native_8k'=>false,'alt'=>'ISOLATED unapproved synthetic CODE fixture'];
 $part_ids=['isolated-qa-download-part'];$manifest=['bundle_id'=>$part_ids[0],'records'=>[$record],'looks'=>[]];$archive=$folder.'/part.zip';$zip=new ZipArchive();$zip->open($archive,ZipArchive::CREATE);$zip->addFromString('manifest.json',wp_json_encode($manifest));$zip->addFile($png,$record['file']);$zip->close();$part=['bundle_id'=>$part_ids[0],'url'=>'https://raw.githubusercontent.com/imahmad-malik/check.txt/isolated-qa/part.zip','sha256'=>hash_file('sha256',$archive),'bytes'=>filesize($archive)];$index=['version'=>1,'release'=>'isolated-test-only','parts'=>[$part]];file_put_contents($index_path,wp_json_encode($index));
 $interceptor=static function($pre,$args,$url)use(&$calls,$archive){$calls[]=['url'=>$url,'sslverify'=>$args['sslverify']??null,'redirection'=>$args['redirection']??null,'stream'=>$args['stream']??null,'limit_response_size'=>$args['limit_response_size']??null];copy($archive,$args['filename']);return ['headers'=>['content-length'=>(string)filesize($archive)],'body'=>'','response'=>['code'=>200,'message'=>'OK'],'cookies'=>[],'filename'=>$args['filename']];};add_filter('pre_http_request',$interceptor,10,3);
 $state=bixie_download_start();qd_assert('Trusted download starts without fetching until an explicit step',$state['status']==='running'&&$state['cursor']===0&&count($calls)===0);$state=bixie_download_step();qd_assert('One part per request verifies and advances persisted state',$state['status']==='complete'&&$state['cursor']===1&&isset(((array)get_option('bixie_media_bundle_parts',[]))[$part_ids[0]]));
 qd_assert('Transport requests preserve TLS verification and streaming bounds',count($calls)===1&&$calls[0]['sslverify']===true&&$calls[0]['redirection']===0&&$calls[0]['stream']===true&&$calls[0]['limit_response_size']===25*MB_IN_BYTES+1);
 bixie_download_start();$state=bixie_download_step();qd_assert('Resuming an already verified exact archive avoids a second download',count($calls)===1&&$state['status']==='complete');
 remove_filter('pre_http_request',$interceptor,10);$interceptor=static function($pre,$args,$url){return ['headers'=>['location'=>'https://example.invalid/forbidden.zip'],'body'=>'','response'=>['code'=>302,'message'=>'Found'],'cookies'=>[]];};add_filter('pre_http_request',$interceptor,10,3);$changed=$part;$changed['bundle_id']='isolated-qa-download-redirect';$changed['sha256']=str_repeat('a',64);$rejected=false;try{bixie_fetch_release_part($changed);}catch(Throwable $error){$rejected=str_contains($error->getMessage(),'redirect');}qd_assert('Redirect outside trusted release hosts is rejected',$rejected);
 remove_filter('pre_http_request',$interceptor,10);$interceptor=static function($pre,$args,$url)use($archive){copy($archive,$args['filename']);return ['headers'=>[],'body'=>'','response'=>['code'=>200,'message'=>'OK'],'cookies'=>[]];};add_filter('pre_http_request',$interceptor,10,3);$rejected=false;try{bixie_fetch_release_part($changed);}catch(Throwable $error){$rejected=str_contains($error->getMessage(),'SHA-256');}qd_assert('Incorrect trusted-index SHA-256 rejects the downloaded archive',$rejected);
 $changed=$part;$changed['bundle_id']='isolated-qa-wrong-expected-id';$rejected=false;try{bixie_fetch_release_part($changed);}catch(Throwable $error){$rejected=str_contains($error->getMessage(),'part ID');}qd_assert('Wrong expected part ID is rejected before extraction/registration',$rejected&&!isset(((array)get_option('bixie_media_bundle_parts',[]))[$changed['bundle_id']]));
}catch(Throwable $error){$failure=$error->getMessage();}
finally{if($interceptor){remove_filter('pre_http_request',$interceptor,10);}if($old_index===null){if(is_file($index_path)){unlink($index_path);}}else{file_put_contents($index_path,$old_index);}if($old_state===null){delete_option('bixie_media_download_state');}else{update_option('bixie_media_download_state',$old_state,false);}$parts=(array)get_option('bixie_media_bundle_parts',[]);foreach($part_ids as $id){if(isset($parts[$id])){bixie_bundle_remove_stage(bixie_bundle_base().'/'.$id);unset($parts[$id]);}}update_option('bixie_media_bundle_parts',$parts,false);if(is_dir($folder)){bixie_bundle_remove_stage($folder);}}
$report=['environment'=>['wordpress'=>get_bloginfo('version'),'php'=>PHP_VERSION],'method'=>'Actual isolated WordPress controller/verifier/state execution with explicitly simulated WP HTTP transport. No final production URL or live remote distribution was tested.','passed'=>$failure===null,'checks'=>$tests,'failure'=>$failure,'approvedProductionImages'=>0];$json=wp_json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)."\n";if(!empty($argv[2])){file_put_contents($argv[2],$json);}echo $json;exit($report['passed']?0:1);
